//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qualitas_Backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TopicTemplate()
        {
            this.CriteriaTemplates = new HashSet<CriteriaTemplate>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool isCritical { get; set; }
        public int TemplateId { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CriteriaTemplate> CriteriaTemplates { get; set; }
        public virtual EvaluationTemplate EvaluationTemplate { get; set; }
    }
}
