export const ActionType = {
  LOAD_USERS: "LOAD_USERS",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  ARCHIVE_USER: "ARCHIVE_USER",

  LOAD_ARCHIVED_USERS: "LOAD_ARCHIVED_USERS",
  UNARCHIVE_USER: "UNARCHIVE_USER",
  DELETE_USER: "DELETE_USER",

  LOAD_TEMPLATE_LIST: "LOAD_TEMPLATE_LIST",
  LOAD_TEMPLATE: "LOAD_TEMPLATE",
  CREATE_TEMPLATE: "CREATE_TEMPLATE",
  UPDATE_TEMPLATE: "EDIT_TEMPLATE",
  DELETE_TEMPLATE: "DELETE_TEMPLATE",

  LOAD_PROJECTS: "LOAD_PROJECTS",
  LOAD_PROJECT: "LOAD_PROJECT",
  CREATE_PROJECT: "CREATE_PROJECT",
  UPDATE_PROJECT: "EDIT_PROJECT",
  DELETE_PROJECT: "DELETE_PROJECT"
};
