export const ActionType = {
  LOAD_USERS: "LOAD_USERS",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  ARCHIVE_USER: "ARCHIVE_USER",

  LOAD_ARCHIVED_USERS: "LOAD_ARCHIVED_USERS",
  UNARCHIVE_USER: "UNARCHIVE_USER",
  DELETE_USER: "DELETE_USER",
};
